apiVersion: apps/v1
kind: Deployment
metadata:
  name: comp-reg-api
  labels:
    app: comp-reg-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comp-reg-api
  template:
    metadata:
      labels:
        app: comp-reg-api
    spec:
      containers:
        - name: comp-reg-api
          image: comp-reg-api:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: COMPANIES_FILE
              value: "data/companies.csv"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"